"""Tests for click commands."""

from __future__ import annotations

from datetime import date
import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from click.testing import CliRunner
from sqlalchemy.orm import Session

from src.cli.main import cli
from src.db.session import create_all_tables, create_database_engine, create_session_factory
from src.models.artifact import Artifact
from src.models.enums import FeedbackTargetType, FeedbackType, SourceType
from src.repositories.feedback_repository import FeedbackRepository


class StubLLMClient:
    """Simple stub used by CLI tests to avoid live LLM calls."""

    def __init__(self) -> None:
        """Track prompts passed through the CLI path."""

        self.calls: list[dict[str, object]] = []

    def generate(self, prompt: str, **kwargs) -> str:
        """Return deterministic JSON for enrichment and llm relevance steps."""

        self.calls.append({"prompt": prompt, **kwargs})
        cache_key = str(kwargs.get("cache_key") or "")
        if cache_key.startswith("relevance_v2_"):
            return json.dumps({"score": 4, "reason": "Highly relevant to web security."})
        return json.dumps(
            {
                "summary_l1": "Generated by CLI test.",
                "tags": ["cli-test", "browser-security", "sandboxing"],
            }
        )


class CommandCliTestCase(unittest.TestCase):
    """Integration tests for CLI commands."""

    def setUp(self) -> None:
        """Create an isolated workspace and database."""

        self.runner = CliRunner()
        self.temp_dir = tempfile.TemporaryDirectory()
        self.workspace = Path(self.temp_dir.name)
        self.database_path = self.workspace / "test.db"
        self.database_url = f"sqlite+pysqlite:///{self.database_path}"
        self.engine = create_database_engine(self.database_url)
        create_all_tables(self.engine)
        self.session_factory = create_session_factory(self.engine)

    def tearDown(self) -> None:
        """Dispose test resources."""

        self.engine.dispose()
        self.temp_dir.cleanup()

    def test_report_command_generates_file(self) -> None:
        """report --type daily should produce a markdown file."""

        with self.runner.isolated_filesystem(temp_dir=self.workspace):
            result = self.runner.invoke(
                cli,
                [
                    "--database-url",
                    self.database_url,
                    "report",
                    "--type",
                    "daily",
                    "--date",
                    "2026-03-11",
                ],
            )

            self.assertEqual(result.exit_code, 0, result.output)
            self.assertTrue(Path("data/reports/daily/2026-03-11.md").exists())

    def test_run_command_executes_pipeline(self) -> None:
        """run --skip-crawl should normalize, enrich, llm-score, and report."""

        stub_llm = StubLLMClient()

        with self.runner.isolated_filesystem(temp_dir=self.workspace):
            raw_dir = Path("data/raw")
            raw_dir.mkdir(parents=True, exist_ok=True)
            (raw_dir / "sample.json").write_text(
                json.dumps(
                    {
                        "source": "NDSS",
                        "source_type": "papers",
                        "fetched_at": "2026-03-11T08:00:00+00:00",
                        "items": [
                            {
                                "title": "CLI Pipeline Paper",
                                "authors": ["Alice Example"],
                                "conference": "NDSS 2026",
                                "year": 2026,
                                "source_type": "papers",
                                "source_url": "https://example.com/ndss/listing",
                                "paper_url": "https://example.com/ndss/cli-pipeline-paper",
                                "abstract": "A browser security paper for CLI testing.",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )

            with patch("src.cli.process.build_llm_client", return_value=stub_llm):
                today = date.today().isoformat()
                result = self.runner.invoke(
                    cli,
                    [
                        "--database-url",
                        self.database_url,
                        "run",
                        "--skip-crawl",
                        "--provider",
                        "openai",
                        "--report-type",
                        "daily",
                        "--date",
                        today,
                    ],
                )

            self.assertEqual(result.exit_code, 0, result.output)
            self.assertIn("Normalized 1 artifact entries", result.output)
            self.assertIn("Enriched 1 artifacts", result.output)
            self.assertIn("LLM relevance scored 1 artifacts", result.output)
            self.assertIn("Scored 1 artifacts", result.output)
            self.assertTrue(Path(f"data/reports/daily/{today}.md").exists())
            self.assertEqual(len(stub_llm.calls), 2)

            session: Session = self.session_factory()
            try:
                artifact = session.query(Artifact).filter(Artifact.title == "CLI Pipeline Paper").one()
                self.assertEqual(artifact.summary_l1, "Generated by CLI test.")
                self.assertEqual(artifact.tags, ["cli-test", "browser-security", "sandboxing"])
                self.assertEqual(artifact.score_breakdown["llm_relevance_score"], 0.8)
                self.assertIsNotNone(artifact.final_score)
            finally:
                session.close()

    def test_feedback_command_end_to_end(self) -> None:
        """feedback command should create a persisted event end-to-end."""

        artifact = self._save_artifact("CLI Feedback Artifact")

        result = self.runner.invoke(
            cli,
            [
                "--database-url",
                self.database_url,
                "feedback",
                "--artifact-id",
                str(artifact.id),
                "--type",
                "like",
            ],
        )

        self.assertEqual(result.exit_code, 0, result.output)

        session: Session = self.session_factory()
        try:
            events = FeedbackRepository(session).list_for_target(FeedbackTargetType.ARTIFACT, str(artifact.id))
            self.assertEqual(len(events), 1)
            self.assertEqual(events[0].feedback_type, FeedbackType.LIKE)
        finally:
            session.close()

    def test_cleanup_ccs_command_deletes_non_full_paper_entries(self) -> None:
        """cleanup-ccs should delete ACM CCS poster/workshop-style entries only."""

        self._save_artifact("Poster: Browser Isolation Demo Board", source_name="ACM CCS")
        self._save_artifact("SoK: Java Deserialization Security", source_name="ACM CCS")
        self._save_artifact("Poster: Non-CCS Entry", source_name="NDSS")

        result = self.runner.invoke(
            cli,
            [
                "--database-url",
                self.database_url,
                "cleanup-ccs",
            ],
        )

        self.assertEqual(result.exit_code, 0, result.output)
        self.assertIn("Cleaned 1 ACM CCS non-full-paper artifacts", result.output)
        self.assertIn("Poster: Browser Isolation Demo Board", result.output)

        session: Session = self.session_factory()
        try:
            remaining_titles = {
                artifact.title
                for artifact in session.query(Artifact).all()
            }
            self.assertNotIn("Poster: Browser Isolation Demo Board", remaining_titles)
            self.assertIn("SoK: Java Deserialization Security", remaining_titles)
            self.assertIn("Poster: Non-CCS Entry", remaining_titles)
        finally:
            session.close()

    def _save_artifact(self, title: str, source_name: str = "NDSS") -> Artifact:
        """Persist one artifact for CLI tests."""

        session: Session = self.session_factory()
        try:
            artifact = Artifact(
                title=title,
                authors=["Alice Example"],
                year=2026,
                source_type=SourceType.PAPERS,
                source_tier="top-tier",
                source_name=source_name,
                source_url=f"https://example.com/{title.lower().replace(' ', '-')}",
            )
            session.add(artifact)
            session.commit()
            session.refresh(artifact)
            return artifact
        finally:
            session.close()
