"""Theme ORM model."""

from __future__ import annotations

import uuid

from sqlalchemy import Enum as SAEnum, Integer, JSON, String, Text
from sqlalchemy.ext.mutable import MutableDict, MutableList
from sqlalchemy.orm import Mapped, mapped_column

from src.db.base import Base, TimestampedModel
from src.models.enums import ThemeStatus


def _enum_values(enum_cls: type[ThemeStatus]) -> list[str]:
    """Return enum values for SQLAlchemy enum storage."""

    return [item.value for item in enum_cls]


def _generate_uuid() -> str:
    """Return a string UUID for theme identifiers."""

    return str(uuid.uuid4())


class Theme(TimestampedModel, Base):
    """Research sub-area cluster generated by the clustering pipeline."""

    __tablename__ = "themes"

    theme_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        unique=True,
        index=True,
        default=_generate_uuid,
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False, index=True)
    description: Mapped[str | None] = mapped_column(Text)
    keywords: Mapped[list[str]] = mapped_column(
        MutableList.as_mutable(JSON),
        nullable=False,
        default=list,
    )
    artifact_ids: Mapped[list[int]] = mapped_column(
        MutableList.as_mutable(JSON),
        nullable=False,
        default=list,
    )
    artifact_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    paper_count_by_year: Mapped[dict[str, int]] = mapped_column(
        MutableDict.as_mutable(JSON),
        nullable=False,
        default=dict,
    )
    methodology_tags: Mapped[list[str]] = mapped_column(
        MutableList.as_mutable(JSON),
        nullable=False,
        default=list,
    )
    open_questions: Mapped[list[str]] = mapped_column(
        MutableList.as_mutable(JSON),
        nullable=False,
        default=list,
    )
    trend_direction: Mapped[str | None] = mapped_column(String(20))
    status: Mapped[ThemeStatus] = mapped_column(
        SAEnum(
            ThemeStatus,
            values_callable=_enum_values,
            native_enum=False,
            validate_strings=True,
        ),
        nullable=False,
        index=True,
        default=ThemeStatus.CANDIDATE,
    )
    generation_version: Mapped[str] = mapped_column(String(50), nullable=False, index=True, default="v1")
    week_id: Mapped[str] = mapped_column(String(10), nullable=False, index=True)
